"""
Ablation study visualization: modality contribution heatmap.

Reads ablation_results.csv (generated by run_ablation.py) and plots
a heatmap of ROC-AUC by (split × ablation_mode) for the best CLIP
and best ViLT models.

Output:
  analysis_outputs/fig_ablation_clip.png
  analysis_outputs/fig_ablation_vilt.png
"""

import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

ABLATION_CSV = Path("ablation_results.csv")
OUT_DIR      = Path("analysis_outputs")

SPLITS    = ["dev_seen", "dev_unseen", "test_seen", "test_unseen"]
ABLATIONS = ["multimodal", "text_only", "image_only"]
MODE_LABELS = ["Multimodal\n(both)", "Text only\n(image zeroed)", "Image only\n(text zeroed)"]


def load_ablation_results() -> dict:
    """
    Returns dict:
        {model_family: {config: {split: {ablation: {metric: value}}}}}
    """
    if not ABLATION_CSV.exists():
        print(f"  [warning] {ABLATION_CSV} not found — run run_ablation.py first.")
        return {}

    results: dict = {}
    with open(ABLATION_CSV, newline="") as f:
        for row in csv.DictReader(f):
            fam    = row["model_family"]
            cfg    = row["config"]
            split  = row["split"]
            ablation = row["ablation"]
            results.setdefault(fam, {}).setdefault(cfg, {}).setdefault(split, {})[ablation] = row

    return results


def plot_ablation(data: dict, model_family: str, out_path: Path) -> None:
    """Plot a 3×4 heatmap: rows=ablation modes, cols=splits."""
    if model_family not in data:
        print(f"  [warning] No ablation data for {model_family} — skipping.")
        return

    # Use first (only) config per family
    configs = list(data[model_family].keys())
    if not configs:
        return
    config = configs[0]
    config_data = data[model_family][config]

    # Build 2D matrix: rows=ablation, cols=split
    matrix = np.zeros((len(ABLATIONS), len(SPLITS)))
    for c, ablation in enumerate(ABLATIONS):
        for s, split in enumerate(SPLITS):
            val = config_data.get(split, {}).get(ablation, {}).get("auroc", "")
            matrix[c, s] = float(val) if val else 0.0

    fig, ax = plt.subplots(figsize=(9, 4))
    im = ax.imshow(matrix, cmap="YlOrRd", vmin=0.5, vmax=0.85, aspect="auto")
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="ROC-AUC")

    ax.set_xticks(range(len(SPLITS)))
    ax.set_xticklabels(SPLITS, fontsize=10)
    ax.set_yticks(range(len(ABLATIONS)))
    ax.set_yticklabels(MODE_LABELS, fontsize=10)

    for c in range(len(ABLATIONS)):
        for s in range(len(SPLITS)):
            val = matrix[c, s]
            color = "white" if val > 0.7 else "black"
            ax.text(s, c, f"{val:.4f}", ha="center", va="center",
                    fontsize=11, fontweight="bold", color=color)

    label_str = "CLIP" if model_family == "CLIP" else "ViLT"
    ax.set_title(
        f"Ablation Study — {label_str} ({config})\nROC-AUC by split and modality",
        fontsize=12,
    )
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Saved: {out_path}")


def main() -> None:
    OUT_DIR.mkdir(exist_ok=True)
    results = load_ablation_results()

    print("Ablation heatmaps...\n")
    plot_ablation(results, "CLIP", OUT_DIR / "fig_ablation_clip.png")
    plot_ablation(results, "ViLT", OUT_DIR / "fig_ablation_vilt.png")


if __name__ == "__main__":
    main()
